services:
    app: { build: ., ports: ["5173:5173","8000:8000"], depends_on: [db,redis,mailhog] }
    db: { image: postgres:16, environment: { POSTGRES_PASSWORD: secret, POSTGRES_DB: edumvp }, ports: ["5432:5432"] }
    redis: { image: redis:7, ports: ["6379:6379"] }
    mailhog: { image: mailhog/mailhog, ports: ["8025:8025"] }
